requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sjmm_util"
version = "0.0.1"

dependencies = [
 "numpy",
 "pandas",
 "matplotlib",
 "astropy",
 "reproject",
 "scipy",
 "scikit-image"
]
